// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU1CWqNf5U8uWke1edXLpTNiY2T_eQ658',
    appId: '1:356191281196:web:6b31831c7130d1441df189',
    messagingSenderId: '356191281196',
    projectId: 'vet-flutter',
    authDomain: 'vet-flutter.firebaseapp.com',
    storageBucket: 'vet-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWte17-P-zX6s7eF9Z3BNItpgiQGbQ4GM',
    appId: '1:356191281196:android:d9d5552abe4188e41df189',
    messagingSenderId: '356191281196',
    projectId: 'vet-flutter',
    storageBucket: 'vet-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeeQF3WWvUKdVG4YRG0muIrdjupB1wpJ0',
    appId: '1:356191281196:ios:2b25fd4b47b25f8c1df189',
    messagingSenderId: '356191281196',
    projectId: 'vet-flutter',
    storageBucket: 'vet-flutter.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeeQF3WWvUKdVG4YRG0muIrdjupB1wpJ0',
    appId: '1:356191281196:ios:2b25fd4b47b25f8c1df189',
    messagingSenderId: '356191281196',
    projectId: 'vet-flutter',
    storageBucket: 'vet-flutter.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCU1CWqNf5U8uWke1edXLpTNiY2T_eQ658',
    appId: '1:356191281196:web:27155b71fb2817c31df189',
    messagingSenderId: '356191281196',
    projectId: 'vet-flutter',
    authDomain: 'vet-flutter.firebaseapp.com',
    storageBucket: 'vet-flutter.firebasestorage.app',
  );
}
